### ISSUE TITLE
[Question] Will this re-enable Google Sign-in?

### ISSUE THREAD

**Issue by warren-bank** [TimScriptov/ApkSignatureKill#1]
I haven't taken a deep dive into your methodology (yet). I'm curious how that differs to [ApkSignatureKiller](https://github.com/L-JINBIN/ApkSignatureKiller). But my real question is whether it brings a new capability.. the ability to pass whatever apk validation occurs during the Google Sign-in login process?

Let use [Join](https://apkpure.com/join-by-joaoapps/com.joaomgcd.join) as an example..

```bash
apktool d /path/to/join.apk
apktool b /path/to/join -o /path/to/modified_join_unsigned.apk

apksigner sign --v1-signing-enabled true --v2-signing-enabled true --v3-signing-enabled true --ks "$keystore_file" --ks-key-alias "$keystore_alias" --ks-pass "pass:${keystore_pass}" --pass-encoding "utf-8" --key-pass "pass:${key_pass}" --out /path/to/modified_join_signed.apk /path/to/modified_join_unsigned.apk
```

* a Google Sign-in dialog gates the launcher activity
* without making any modifications to the apk aside from changing its signature, Google Sign-in fails.. as indicated by a toast to display the error message

Using _ApkSignatureKiller_, this still doesn't work; Google Play Services must detect that the apk isn't signed by the original developer.. though I'm not sure how this all plays out. If anybody reading this understands the flow (at a high level).. I'd really appreciate a quick summary.

**Comment by timscriptov** [comment]
Hello @warren-bank !
This project is a port of https://github.com/L-JINBIN/ApkSignatureKiller for android. The project has no revolutionary solutions.

The project was created with the aim of attracting other developers who can create a good software product on the basis of this project.

**Comment by warren-bank** [comment]
Thanks for the response! I didn't realize that was the goal of this project.

What's funny is that I consider the original too much tooling.. and just manually copy the [one smali file](https://github.com/L-JINBIN/ApkSignatureKiller/blob/master/src/cc/binmt/signature/PmsHookApplication.smali) directly into my project, as needed; just need to update the hard-coded base64 signature, update the super class (if necesssary), and update the _AndroidManifest.xml_ to use this class for the Application.. with one additional caveat, to remove the _final_ flag from the class originally used for the Application (if present).

I was _really_ hoping this project might approach the problem from a different angle, and provide an easy way to keep Google Sign-in functional in the resulting app. :smiley:
